insert into Community (name, title, owner_id, description) values ('announcements', 'turpis donec posuere metus', 1, 'diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque');
insert into Community (name, title, owner_id, description) values ('funny', 'venenatis', 1, 'nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia');
insert into Community (name, title, owner_id, description) values ('AskReddit', 'amet lobortis sapien sapien non', 1, 'vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel');
insert into Community (name, title, owner_id, description) values ('gaming', 'primis in faucibus orci luctus', 1, 'vestibulum ante ipsum primis in faucibus orci luctus et ultrices');
insert into Community (name, title, owner_id, description) values ('aww', 'tincidunt nulla mollis molestie lorem', 1, 'posuere cubilia curae nulla dapibus');
insert into Community (name, title, owner_id, description) values ('Music', 'ut odio cras', 1, 'ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst');
insert into Community (name, title, owner_id, description) values ('pics', 'habitasse platea dictumst etiam faucibus', 1, 'montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur');
insert into Community (name, title, owner_id, description) values ('worldnews', 'volutpat in congue', 1, 'libero rutrum ac lobortis vel dapibus at diam nam tristique tortor eu');
insert into Community (name, title, owner_id, description) values ('science', 'viverra', 1, 'nascetur ridiculus mus vivamus vestibulum sagittis sapien cum');
insert into Community (name, title, owner_id, description) values ('movies', 'orci mauris lacinia sapien quis', 1, 'duis aliquam convallis nunc proin at turpis');
insert into Community (name, title, owner_id, description) values ('todayilearned', 'ante ipsum primis', 1, 'tincidunt in leo');
insert into Community (name, title, owner_id, description) values ('videos', 'amet', 1, null);
insert into Community (name, title, owner_id, description) values ('news', 'nulla neque libero convallis eget', 1, 'lorem');
insert into Community (name, title, owner_id, description) values ('Showerthoughts', 'id mauris vulputate elementum', 1, 'id justo sit amet sapien dignissim');
insert into Community (name, title, owner_id, description) values ('Jokes', 'mauris vulputate elementum nullam', 1, 'venenatis non sodales sed tincidunt eu felis');
insert into Community (name, title, owner_id, description) values ('food', 'ullamcorper purus sit amet', 1, 'odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui');
insert into Community (name, title, owner_id, description) values ('askscience', 'vestibulum eget vulputate ut ultrices', 1, 'id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec');
insert into Community (name, title, owner_id, description) values ('IAmA', 'turpis', 1, 'augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt');
insert into Community (name, title, owner_id, description) values ('EarthPorn', 'id', 1, 'montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient');
insert into Community (name, title, owner_id, description) values ('gifs', 'placerat praesent blandit nam nulla', 1, 'volutpat');
insert into Community (name, title, owner_id, description) values ('nottheonion', 'eget tempus vel pede', 1, 'non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in');
insert into Community (name, title, owner_id, description) values ('books', 'vel nulla', 1, 'purus phasellus in felis donec semper sapien a libero');
insert into Community (name, title, owner_id, description) values ('DIY', 'felis donec semper sapien a', 1, 'velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat');